### ISSUE TITLE
[Bug] Wwise *.bnk files cut off when extracted (and converted)

### ISSUE THREAD

**Issue by newby24** [vgmstream/vgmstream#1008]
Hello.

I had noticed an issue, where I tried to extract and convert a *.bnk file from an Unreal Engine 4 game.
The sound is cut off near the end when played back/converted

The game also has *.wem files stored separately, and those do play/convert fine (the whole sound file is played perfectly without any cutoffs)

So either the splitting or the conversion is failing somewhere along the way.

I am attaching a sample of the *.wem file that plays fine without any cutoffs and a sample of a *.bnk file that is failing to convert properly (this applies to all *.bnk files found)
[bnk and wem.zip](https://github.com/vgmstream/vgmstream/files/7486880/bnk.and.wem.zip)

**Comment by bnnm** [comment]
It's correct they are cut off. Wwise .bnk (loaded in memory) can contain partial files, used to start playback faster while full the .wem streams from disk.

If you have a sound in .bnk and .wem, that usually means the .bnk sound will be used for preloading.

I've added a [pre] mark in the bnk entries to make it clearer.

**Comment by newby24** [comment]
So it is more than likely that the audio file is loaded from the *.BNK file in advance, while the game plays the full version of said audiofile from a different file when needed?

Since I was confused when I extracted the *.bnk file, the total file size matched the size of the *.bnk file, but when I wanted to convert/play them, it just gave me files which cut off, very irregularly I might add.

Thanks for the answer in advance.

**Comment by bnnm** [comment]
Yes, the whole .bnk is kept loaded in memory, and used to partially play while the actual .wem loads. This is because loading a .wem takes some small time, and this way they can start playing audio without delay.

The .bnk audio is the same as the .wem but simply truncated after a point. The correct "truncated" time isn't exactly detected by vgmstream, but since those files are uninteresting (as in, there should always be a full .wem elsewhere) shouldn't matter much. Not all audio in .bnk is like this though (mix of bnk-only songs and partial audio), devs can configure this cut off time.

You may want to check this tool to see how .bnk config internally works, and generate named .txtp that correctly play full .bnk audio or .wem when needed: https://github.com/bnnm/wwiser/

**Comment by newby24** [comment]
Thank you so much, I appreciate the help 😄
