### ISSUE TITLE
[Bug] [Regression?] PSP AT3 looping doesn't work anymore in foobar2000

### ISSUE THREAD

**Issue by R4to0** [vgmstream/vgmstream#1013]
It's been since a few versions that looping for this type of song stopped working properly, the song only plays once and there's no fade out, not respecting the settings.

![image](https://user-images.githubusercontent.com/3608184/141538108-3a0135d8-46cb-4d25-99b1-2d571565158d.png)

Original sample (Ape Escape on the Loose for PSP)
[19 Soichi Terada - New Freezeland ~ Snowy Mammoth.zip](https://github.com/vgmstream/vgmstream/files/7530570/19.Soichi.Terada.-.New.Freezeland.Snowy.Mammoth.zip)

Expected looping (I converted to m4a long ago when looping was working as expected):
[19 Soichi Terada - New Freezeland ~ Snowy Mammoth.zip](https://github.com/vgmstream/vgmstream/files/7530574/19.Soichi.Terada.-.New.Freezeland.Snowy.Mammoth.zip)

**Comment by bnnm** [comment]
Those files are broken/incorrectly ripped and contain extra data. Download an updated rip (original files should be .sgd), or remove that extra data manually with a hex editor ("SGDX" garbage at the end).

As for why they looped before, some extra validations were added to avoid playing broken files, as otherwise would cause problems elsewhere. There is a an exception for .at3 since there are a bunch of broken .at3 around, but it can't do looping.

**Comment by R4to0** [comment]
Thanks for the headsup. Just for reference, I got the rip from Zophar website.
