### ISSUE TITLE
[Bug] Wii Sports RWSD

### ISSUE THREAD

**Issue by milesthecreator** [vgmstream/vgmstream#1061]
Attempting to play the file results to a static sound. I've provided 2 examples:
https://drive.google.com/file/d/1CA4uG9R6BjecuJZA2eSySoGLLwDzj0sT/view?usp=sharing

**Comment by bnnm** [comment]
Data is a mix of dsp, pcm16 and more dsp, with no apparent offsets, so probably this "format" isn't meant to be extracted like this and needs info from the brsar to actually work.

**Comment by bnnm** [comment]
Because .brsar is a complex cue format, and RWSD is just a section within with no relation to data offset (not an audio format, current support is just a hack), I don't see a way to properly support this case in vgmstream.

Instead I've lowered RWSD's priority so TXTH goes first, and rejected files that have excess data (like this one).

A more proper way to handle this I think would be using [brawlbox](https://github.com/libertyernie/brawltools/releases) to find correct header and data offsets and make txths (or extract).

For example, BGM_Tutorial points to RWSD index 19 (notice there are multiple RWSDs, each represents a song):.

![image1](https://user-images.githubusercontent.com/22844311/210152365-d1010471-8aa0-40b0-a8dc-3d4c4b51eec3.png)


![image2](https://user-images.githubusercontent.com/22844311/210152392-b1e653d8-fbf9-4092-8f7d-b003fc448797.png)
