### ISSUE TITLE
[Bug] weird playback with some MSH+MSB files [Le Tour de France: 1903-2003 - Centenary Edition (PS2)]

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1086]
so, i came across a PS2 game that has these MSB+MSH files. i tried to play at least one of them (MIHBODY.[MSH+MSB]) with foobar2000 plus an recent version of vgmsteam component. what i get is some sort of weird playback where the subsongs in there just kinda repeat themselves for one second? something tells me they're supposed to be 2-channel sounds.

i don't have any problems with playing BANK1.[MSH+MSB] since the subsongs in there play rather "flawlessly", so to speak.

anyway, here are the samples.
[[le_tour_de_france_1903-2003_centenary_edition]ps2_msb+msh.7z](https://krakenfiles.com/view/5uqxv6T69x/file.html)

**Comment by bnnm** [comment]
I think devs are using some hack, where MUSIC.MSB has a bunch of .mih and MIHBODY.MSB their .mib and they load those manually (.msh are just used for offsets).

Doesn't seem like something the format would support by itself since there are no filenames pointing to each other, unless more games doing this are found. Apart from extracting .mih/.mib you could use something like this:

**music.txth** (open directly)
```
codec = PSX

# get music.msh's .mih header offset 
header_file = MUSIC.MSH
subsong_count = @0x08
subsong_spacing = 0x10
base_offset = @0x14

# read .mih data
subsong_spacing = 0x00
header_file = MUSIC.MSB

channels = @0x08
sample_rate = @0x0c
interleave = @0x10
#0x14: frame count
base_offset = 0x00
subsong_spacing = 0x10

# get .mib body offset+size
header_file = MIHBODY.MSH
body_file = MIHBODY.MSB
data_size = @0x0c
start_offset = @0x14
num_samples = data_size
```

**Comment by modusc896d352** [comment]
that should do it.
