### ISSUE TITLE
[Bug] Possible Trojan in windows r1776 build files

### ISSUE THREAD

**Issue by cppctamber** [vgmstream/vgmstream#1215]
The windows download of the vgmstream command-line tools and Winamp archive are triggering trogan warnings.

Steps to recreate
- download with latest chrome, fails due to reported virus 
- download with latest edge, fails due to reported virus
- download with latest firefox, downloads
- windows defender, reports file as containing `Trojan:Win32/Wacatac.B!ml`
- malwarebytes premium, reports zip contains malware with their id `365983348`

I tried with some online file checkers and it seems bitdefender is the only one that flags it as suspicious.

**Comment by kddlb** [comment]
It may be a false positive. As usual.

**Comment by kode54** [comment]
Would be weird if Github's own CI images were suddenly infected with viruses.

**Comment by kode54** [comment]
Needs someone to submit the binaries to Microsoft as false positives. Which requires repacking them in a password protected ZIP and submitting. They give full directions on their submission site.

**Comment by kode54** [comment]
Okay, cool, www.bitdefender.com is refusing to load here.

**Comment by cppctamber** [comment]
I am now getting the warning on the winamp archive too, which I didn't originally.
Malwarebytes also passed the command line archive the first time around but it now reports that it contains malware.

**Comment by kode54** [comment]
I could stop providing Windows binaries, and ask people to just download MinGW and build their own, but then they'll probably start reporting MinGW as a virus.

**Comment by bnnm** [comment]
I decompiled last time this came up and seemed some code MSVC injects that trips virus scanners. Changing the MSVC version (older?) fixed it for a while, but I guess github updated it again, [see here](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md).

Probably sooner or later they'll update MSVC and will be fixed, or maybe there is some compile flag that could improve this. Meanwhile here are MinGW/GCC versions I compile myself, that don't seem to trigger virus warnings:
https://github.com/bnnm/vgmstream-builds/tree/master/bin (cli/winamp only, since foobar is locked to MSVC)

**Comment by kddlb** [comment]
I added a warning to the [downloads page](https://dl.vgmstream.org)

**Comment by bnnm** [comment]
windows defender and virustotal don't seem to whine about r1800 and beyond, so no need to keep this open I think.

**Comment by Pysis868** [comment]
r1951: https://www.virustotal.com/gui/file/c28d08de245ff805d15770e635d5a37cf6235185a9eca95cf7011a620af07bd6
> 2/72
> 
> Bkav Pro: W32.AIDetectMalware
> Rising: Trojan.Kryptik@AI.88 (RDML:nm1j0hZY9isbowrvH
