### ISSUE TITLE
[Request] Zero padding any format according the number of files in the file

### ISSUE THREAD

**Issue by MrShiruba** [vgmstream/vgmstream#1224]
When you extract an archive with foobar2000 (I guess the same applies to using CLI), the numbers appended after the "#" aren't padded. This means that files aren't ordered the same if you are on Windows on Linux. I personally find Linux sorting more natural.

Windows sorting (check the whole number) :
FILE#1
FILE#2
FILE#3
FILE#4
FILE#5
FILE#6
FILE#7
FILE#8
FILE#9
FILE#10
FILE#11

Linux sorting (check char by char) :
FILE#1
FILE#10
FILE#11
FILE#2
FILE#3
FILE#4
FILE#5
FILE#6
FILE#7
FILE#8
FILE#9

But if you add zero before the integer, the file order is the same.
Desired output :
FILE#01
FILE#02
FILE#03
FILE#04
FILE#05
FILE#06
FILE#07
FILE#08
FILE#09
FILE#10
FILE#11

I don't know if this would be easy to implement, but I guess if you are able to know the total number of files in the archive it wouldn't be hard to implement given that I think most files won't exceed 999 files.

**Comment by bnnm** [comment]
Not sure about changing the default, since it's been there for a while. Instead you can override this title, see here and the above posts: https://github.com/vgmstream/vgmstream/issues/277#issuecomment-575892937 (I'll update the docs later).

When converting to .wav in foobar you can just change the format in the *destination* field, without having to set "override title". For example `[$num(%stream_index%,2)] %filename%[-%stream_name%]` may create a name like `01 BGM-EVENT_SAD`.

In CLI you can set the output filename format manually too, like `vgmstream-cli -s 2 -o ?04s_?n.wav BGM.fsb` would make `0002_EVENT_SAD.wav` ([see here](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#testexevgmstream-cli-command-line-decoder)).

**Comment by bnnm** [comment]
No further comments so closing.

**Comment by MrShiruba** [comment]
Oops, indeed I found my own solution using Perl rename with bash, more info here : https://stackoverflow.com/questions/55754/how-to-zero-pad-numbers-in-file-names-in-bash

But I guess the solutions provided above works too. So yes problem solved.
