### ISSUE TITLE
[Request] Audacious Flatpak support and/or Audacious + VGMStream appimage

### ISSUE THREAD

**Issue by Star-X555** [vgmstream/vgmstream#1233]
Primarily because Steam Deck can't compile stuff normally.

**Comment by bnnm** [comment]
I think you should elaborate about what those are, and why vgmstream/audacious couldn't compile normally on them.

**Comment by kode54** [comment]
They want this project to compile the entire audio player and bundle it up, or bundle up builds and list them on Flathub as plugin addons for Audacious, because Steam Deck has no compiler packages, and because installing anything but Flatpak there is painful, because every software update just wipes every package you've installed by any means other than Flatpak or Steam game downloads.

**Comment by bnnm** [comment]
If flatpak/flathub is about having an Audacious pack with all plugins I'd think they need to ask in Audacious repo to do that bundle and include vgmstream.
