### ISSUE TITLE
[Request] Question about stream index and multiple samples in a file

### ISSUE THREAD

**Issue by Powa315** [vgmstream/vgmstream#1271]
Hi, I want to know how the stream index and multiple samples work for files in vgmstream. I'm trying to figure out what they mean for dissidia 012's scd files where they're in the vag format, but all I need to know is if the index and samples mean there's multiple files in one or just one.

**Comment by modusc896d352** [comment]
if an scd file has only one sound (be it a 3-minute music composition or a 30-second jingle) then it's a single file. otherwise, it has multiple sounds stored in one file.

**Comment by bnnm** [comment]
For formats that internally have multple songs (like .scd), stream index is the number of sub-song, where index 1 is first subsong, index 2 is second subsong and so on. If file doesn't have several subsongs, then index is ignored.

You can combine multiple subsongs using [txtp](https://github.com/vgmstream/vgmstream/blob/master/doc/TXTP.md), by making a text file named `(whatever).txtp` near your scd and writting something like this:
```
file.scd #1
file.scd #2
file.scd #3
```
That would play the first 3 subsongs as a single song.

**Comment by Powa315** [comment]
Yeah that's what I've thought, and I've made a txtp file, just not sure how to like make it work, do you need anything else specific with it or a command for vgmstream? And also is it just playback or is it file creation? Cause all I think I need atm is some way to wrap the files together as subsongs in like a container and slap an scd header onto it for what I'm trying to do.

**Comment by bnnm** [comment]
vgmstream is a library/program that plays video game audio files or converts them to wav. If you make that .txtp file, you can play it with vgmstream and listen to how it sounds.

Want you intent to do as you describe it is impossible. vgmstream only plays audio and .scd is not a simple collection of .vag (not like a zip file). You need somebody to make you a program that creates custom .scd with proper data and headers (not easy).

As a recommendation, when asking for help make clearer what you want to do ("make a custom .scd", for modded dissidia voices I guess) and not what you think you need to do ("make txtp files with stream indexes (then later I'll slap a header)").

**Comment by Powa315** [comment]
I see. You're right, I'll be clearer next time. I'd just heard examples of .scds being able to be made by adding the header onto the correct audio format, and all the resources for the format just explain what the header information is so I assumed the process went something like that, so I was trying to ask more general questions about it. Can I ask if there's anything you can tell me about what they're exactly comprised of for the sounds to be read like that by vgmstream?

**Comment by bnnm** [comment]
First, note that there are different game formats with the .scd extension, so what you have heard may not apply to your game.

Here is the code that parses Dissidia 012's .scd: https://github.com/vgmstream/vgmstream/blob/master/src/meta/sscf.c

Format has a header section with N sub-headers (one per subsong) that describe raw data (offset in the file/size/channels/etc), then raw PS-ADPCM data pasted together per subsong.

The game is probably hardcoded to do "read subsong N" commands, then follow whatever is in the sub-header N. So unless you build a proper .scd with all the sub-headers (particularly offsets/sizes) it's unlikely it would play audio correctly.

Best ask in modding communities, since vgmstream just plays audio and making scd is well beyond the scope of this project.
