### ISSUE TITLE
[Bug] Decoding multichannel Vorbis streams scrambles the channels

### ISSUE THREAD

**Issue by KatieFrogs** [vgmstream/vgmstream#1274]
Sample:
[ME_Music_BackInTheGame_Exploration_4_8CH_72BPM.zip](https://github.com/vgmstream/vgmstream/files/10147959/ME_Music_BackInTheGame_Exploration_4_8CH_72BPM.zip)

Opening the files in Audacity shows that the channels get rearranged arbitrarily, left is the ogg file, right is the wav output from vgmstream-cli:
![image](https://user-images.githubusercontent.com/23621460/205477045-2ddfeb16-cf14-4859-bfcf-21a87b93905e.png)

**Comment by KatieFrogs** [comment]
This happens due to the channel mapping that happens in Vorbis: [ogg_vorbis_decoder.c](https://github.com/vgmstream/vgmstream/blob/master/src/coding/ogg_vorbis_decoder.c#L245)
This is an expected behavior that some tools do not support. For example, the sample in the original post was encoded using sox, which maps the channels in a naive way. And Audacity displays them in an unexpected order.
This is resolved by using ffmpeg to encode Ogg Vorbis files.

**Comment by bnnm** [comment]
It seems Audacious imports .ogg and shows channels in Xiph's internal order (FL FC FR SL SR BL BR LFE) rather than WAV's output order (FL FR FC LFE BL BR SL SR) than most players/people expect.

That could be on purpose, but when exporting to WAV it also keeps Xiph's order, making wonky .ogg to .wav conversions (wrong channel layout order). Maybe the issue should be notified.

Note that some devs (like Capcom MT Framework's .sngw) encode vorbis using WAV channel layout (FL FR FC LFE BL BR SL SR) rather than Xiph's (FL FC FR SL SR BL BR LFE), which I suppose lets them skip reordering Xiph-to-WAV. If possible vgmstream detects that and disables reordering.

**Comment by kode54** [comment]
This is the expected order that libvorbis outputs. It’s up to the consumer of libvorbis to shuffle the channel order to match RIFF/WAV. I also have to do this shuffling with libopusfile output in Cog.
