### ISSUE TITLE
Extract the audio stream without decoding / Change the container

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [vgmstream/vgmstream#1320]
I have a `*.wem` audio file that is just 899 KB. Here's the `vgmstream` output:

```
Sample rate: 48.0 kHz
Channels: 2
Channel layout: 3
Stream duration: 1:28.615 (4253539 samples)
Encoding: Opus
Layout: flat
Metadata source: Audiokinetic Wwise RIFF header
Bitrate: 82 kB/s
```

I.e. it's encoded using Opus codec.

The output decoded `*.wav` file is 16,2 MB!

For me it's a waste of space, because previously this file was encoded with a lossy codec. Compressing this `*.wav` file with lossless codecs, e.g. FLAC, will not compress it back to 899 KB. Compressing with a lossy codec will degrade the quality.

Is it possible to just extract the encoded audio stream _**without decoding**_ to raw `*.bin` file and optionally place this stream to regular Ogg/Matroska/WebM/MPEG-TS container that support Opus codec?

**Comment by bnnm** [comment]
This is not possible to do in vgmstream nor is a planned feature.

We encourage preserving original, unmodified data (avoiding decoding, or "transmogrifying" into similar containers) and using player plugins to listen to VGM audio directly. This way one always has the original source with metadata (that can't always be transformed/preserved into other containers), and one may chose to convert into anything later (with the benefit of potential bug fixes).

As for your case, Wwise has 3 Opus variations, plus placing that into a raw .bin would be rather useless, since important info is in the .wem header itself (IOW can't really exist as a raw data, like mp3 or wav PCM could).

**Comment by artemist** [comment]
if you have too much time and like reading specifications it may be possible to convert to a standard container on your own, e.g. I wrote [a script](https://git.mildlyfunctional.gay/artemist/play/src/commit/7f3d2a8c05c17af309cd454a9b65213c74658976/scripts/extract_ktsl2stbin_opus.py) to extract music from Fire Emblem: Three Houses to opus.

This can be a fairly complex endavor since some formats require metadata to decode, e.g. opus packets require a valid streaminfo block and lengths for each packet, and a format may not provide this in a standard format even if the rest of the stream is standard.

Matroska also doesn't support many of the weirder codecs that vgmstream supports, so export would only work on a subset of audio files.

(sorry to necropost, I've just been researching the idea of implementing this and thought the information might be useful)
