### ISSUE TITLE
[Request] Ikemen Villains + Ikemen Prince

### ISSUE THREAD

**Issue by Jewelio** [vgmstream/vgmstream#1334]
イケメンヴィラン 闇夜にひらく悪の恋　恋愛ゲーム・乙女ゲーム (Ikemen Villains: Wrapped in Wicked Romance) https://play.google.com/store/apps/details?id=jp.co.cybird.appli.android.vil.ja&pli=1

Ikémen Prince: Beauty and Her Beast https://play.google.com/store/apps/details?id=jp.co.cybird.appli.android.bjo.en

It would be nice if the hca keys to both of these games were added! (Plus usm key if possible).

**Comment by bnnm** [comment]
.awb from the .apk sound fine, key is the same as "Ikemen Vampire". No idea how usm key is stored sorry.

**Comment by Sukotto-1999** [comment]
Well i first ripped the BGM from Ikemen Villans and Vampire, and that was 2 tracks in BUILDIN_BGM.awb/acb and the opening movie. but Luckily it's re-ripped (a couple tracks in the data). are the files in the current rip obtained from the servers of the game or is hidden in the data.unity3d file? I can't find it without downloading game data without the actual game. also provide instructions how to extract. Thanks @bnnm

**Comment by bnnm** [comment]
Understand that this repo is not for ripping discussion, just this once I guess: you need to install the game and download data from the servers (same with most japanese android/ios games).  .apk typically only have a couple of BGM that play before other data is downloaded (such as the title screen music).

Sometimes like this case there is a "download all" button, otherwise you will need to intercept the urls (or play the whole game). Also depending on the game data may be downloaded to a public dir (can be accessed with regular usb connection) or a private one (needs a rooted phone or emulator to access).

**Comment by Sukotto-1999** [comment]
Maybe there will be a try. thanks bnnm. Next time, i'll contact you thru hcs64 forum.
