### ISSUE TITLE
[Bug] Black Desert wem audio file (vgmstream-r1050-2366) can be played，, but the later version does not support it

### ISSUE THREAD

**Issue by mmorpgfan** [vgmstream/vgmstream#1360]
The old version of the Black Desert wem audio file (vgmstream-r1050-2366) can be played, but the later version does not support it

**Comment by bnnm** [comment]
Post files that don't work.

**Comment by mmorpgfan** [comment]
hello, bnnm  
Black Desert wem audio file Link
https://drive.google.com/file/d/1GA07u0A48mXEeEmdULxdEmJa-DE5qVqT/view?usp=drive_link

**Comment by bnnm** [comment]
Files have missing data, they don't play now to tell you this.

Try ripping them again, making sure your extractor program is working correctly and extracts all files correctly.

**Comment by mmorpgfan** [comment]
Hello, I also thought about this possibility. The strange thing is that the
vgmstream-r1050-2366 version plug-in can work
Thank you for taking the time to respond to my email, thanks

bnnm ***@***.***> 于2023年5月29日周一 05:05写道：

**Comment by bnnm** [comment]
vgmstream-r1050-2366 plays those files because it didn't check the file's integrity. If a file was missing some audio it would still play, but you would get blank/silent audio at the end (may cut sound earlier than it should).

newer vgmstream versions check this integrity, and reject the file if it looks incorrect. This was done because a lot of extraction scripts don't extract correctly files and this is the simplest way to let people know they need to fix that.
