### ISSUE TITLE
[Bug] Fat Princess PS3 - Some .bnk files not playing or playing incorrectly

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1381]
Fat Princess uses Sony .bnk but in a different specification, different specs include stream names. Thus, some .bnk files do not play or play incorrectly.

Sample files in:
https://drive.google.com/file/d/1nheFibw_Dp0WnsKOcaNQqhV2qXpYUtJY/view?usp=drive_link

How to reproduce:
Load some .bnk files to see if it can play correctly.

Notes:
I actually found a way to rip the music from the game, by extracting ADPCM data from .bnk, merging them, and then converting to .genh files, plus, i found a table with stream names as well.

**Comment by bnnm** [comment]
Fixed. Not sure if those stream names are used, will look into it later.

**Comment by Sukotto-1999** [comment]
Actually, there's one more track needed to be fixed, it's under music_07.

**Comment by bnnm** [comment]
I'll take a look as well, but understand fixes are done as personal free time allows it (which usually means only on weekends, sometimes). No need to use ugly GENH hacks for something that will be fixed in a while.

Some stuff is harder and/or takes *a lot* of time to handle, so if there is no immediate response just means you need patience. Even things that may look ignored/stopped (such Torus/Mobiclip) aren't so, but sometimes it takes an immense amount of time.

As a pro-tip, the less time I need to put into research/tests for a bug/request, the higher chance it has to be solved first (see [this request](https://github.com/vgmstream/vgmstream/issues/1369) that provided many, many untouched files and a clear explanation of what it was, what they tried and extra info/links about the format, all which made much easier to fulfill it).

**Comment by bnnm** [comment]
music_07 works now and stream names are now parsed correctly (thanks to EdnessP)
