### ISSUE TITLE
[Request] TXTH/GENH: Layout should say interleave (for mono) if interleave setting is detected.

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1382]
For this request: Expecting a feature, where if interleave setting or value in the GENH header or in the TXTH file is detected if using mono audio, the layout should say "interleave" instead of "flat" (does not apply to codecs that use FFmpeg). I used the interleave setting in TXTH file for my rips of game using SqueakStream, specifically NDS games with this engine, and in my opinion, i expected the layout to say "interleave", but the layout actually says "flat".

**Comment by bnnm** [comment]
Layout info is how vgmstream is processing current audio internally and doesn't really depend on settings. "Interleaved" is not something about the format/engine but how file's data works. Treating mono data as "interleaved" sometimes has internal issues/bugs so it's not simple to change that and not really worth it.

Similarly there are also stereo codecs that use a flat layout (regardless of interleave value) because their data is read linearly; interleaved is used if data is subdivided in chunks per channel. You can also have 2 mono (flat) separate streams combined with with TXTP layers as well --vgmstream calls and processes them as "layered".

**Comment by Sukotto-1999** [comment]
What? The only feature of the support i actually planned. Treating mono data as interleaved will not and i mean NOT be tolerated ever for the feature i actually planned for TXTH/GENH. The feature i actually planned was, it's layout info should say "interleave" like standard formats (specifically .strm or .aus) if interleave setting in the TXTH config or GENH header is detected, but the feature will not treat mono data as interleaved, while mono data is still played in a flat layout.

**Comment by Sukotto-1999** [comment]
Okay fine, looks like i have to close down the issue as not planned for now. Sorry @bnnm.
