### ISSUE TITLE
[Bug] foo_input_vgmstream not working in FB2K 2.x

### ISSUE THREAD

**Issue by NeuroLine** [vgmstream/vgmstream#1407]
Over the last few months, I've been using the foo_input_vgmstream (r1843) component to play EA-XA 4-bit ADPCM v1-encoded ASF files from NHL '99 and 2000 in foobar2000 1.x, but since upgrading to FB2K 2.0, I've noticed that FB2K v2 was incompatible with 1.x components, meaning that the old vgmstream component no longer worked, rendering foobar 2.x unable to decode the ASF audio files from the EA games. I've waited for the r1866 revision to come out on github, hoping it would address the issue, but upon installation of the component, nothing had changed.
Will there be plans to address the issue in later builds of vgmstream?
![image](https://github.com/vgmstream/vgmstream/assets/138359752/cdec89a8-82a9-49d9-8a8c-296fbea99740)
![image](https://github.com/vgmstream/vgmstream/assets/138359752/8f65ecba-c24e-4292-b1a6-0b11b942012c)
![image](https://github.com/vgmstream/vgmstream/assets/138359752/575cf0df-c752-43d3-b934-93f90e6a7d49)
![image](https://github.com/vgmstream/vgmstream/assets/138359752/b4398c08-93a0-4450-96e3-fbe5f0588bc6)

**Comment by NicknineTheEagle** [comment]
Foobar 2.0 is not the problem, the problem is that you're trying to use 32-bit components on 64-bit foobar.

**Comment by bnnm** [comment]
vgmstream's foobar plugin should work fine with v1.x or v2.x, in 32 or 64-bit (there is only one plugin because it includes all versions).

You may need to download and manually install it again though, either on foobar's page or github:
https://github.com/vgmstream/vgmstream/releases/tag/r1866
https://www.foobar2000.org/components/view/foo_input_vgmstream
