### ISSUE TITLE
[Bug] Incorrect file parsing of a certain BTSND (Wii U)

### ISSUE THREAD

**Issue by CyberYoshi64** [vgmstream/vgmstream#1411]
**Affected titles:**
- Wii U "Petit Computer BIG" (TID: 00050000101DFF00)

vgmstream either considers the file to be corrupted or it attempts to play it but not using the appropriate settings, resulting in garbled audio output. In that case, it also reports the length of the audio to be 1:09, which is not correct.

The difference between that game's bootSound and those of other Wii U titles is that the first 8 bytes are 0. The Wii U still accepts it and plays it from start-to-end in a loop.
This is the case in vgmstream as well but it requires changing the first DWORD of the file to 2 in big-endian.

I have to assume the developers of Petit Computer BIG (SmileBoom Co. Ltd.) potentially made the btsnd with improper settings during the submission or vgmstream explicitly checking the first DWORD to be 2 is not ideal. May be a bitmask or revision count of some kind.

Here's the bootSound dumped from the game:
[bootSound.btsnd.zip](https://github.com/vgmstream/vgmstream/files/12456552/bootSound.btsnd.zip)

**Comment by bnnm** [comment]
Basically .btsnd is a semi-raw format that can only be detected using the extension, and nowaways we are trying to avoid supporting those raw-ish formats directly in code since they are so brittle (barely a "format") and using TXTH is pretty easy.

First 32b is 0 if file doesn't loop and 2 if it does. Next 32b is 0 or some unknown value if 0, loop start if 2 (this isn't exclusive to this dev, other games do use this "0 version"). vgmstream only supports the "2" version since the 0 one is so basic might as well be accept any blob of data.

Anyway I'll consider adding support for 0-version files but for the time being unzip this in the folder: [txth.zip](https://github.com/vgmstream/vgmstream/files/12469370/txth.zip)
