### ISSUE TITLE
[Request] VLC Plugin as audio demuxer

### ISSUE THREAD

**Issue by RQWorldblender** [vgmstream/vgmstream#1459]
I just caught wind of this repository, and I got excited at the fact that it can be built natively on Linux distros (and likely other Unix-like OSes).

However, I have realized that while there exists an FFMpeg plugin for VLC, there doesn't exist one yet for vgmstream itself. I ask about this as adding VLC integration would make vgmstream and all its supporting formats more accessible via one of most popular media players, without relying on proprietary media players or command-line interfaces, especially on Linux distros. It also opens up the ability to converted supported formats to others within VLC.

I could possibly work on something like this myself, but I ask here to see if there's interest from others first.

**Comment by bnnm** [comment]
I don't think there is much interest since VLC is more geared towards video, and other audio players have plugins that VLC lacks (like sequenced vgm audio) that potential users would want. There is also the [web player](https://katiefrogs.github.io/vgmstream-web/) that's hard to beat in the 'availability' sense.

But nothing stopping you if you want to make one. Probably would be better to handle in a separate repo and call vgmstream as a lib (there isn't a "public" API at the moment though).

From a quick look it in the past, I think VLC lacks some stuff and has some quirks that make full vgmstream support difficult, including:

- VLC (iirc) seem to use a feed/block model, but vgmstream mostly assumes there is a seekable stream
Many formats need the filesize, some skip + read data around to autodetect corner cases. This can be simulated/ignored somewhat but not sure if models just clash too much.

- some formats need companion files
Because game audio is sometimes fragmented, vgmstream may needs to open other files (such as separate header+data). Particularly useful with TXTH and TXTP. I'd think VLC has a tighter control on opened files.

- some formats (audio banks) have many subsongs
Probably can be handled like FFmpeg's multiple audio streams, but I guess that's more like multiple audio tracks, vgmstream subsongs are like +20 completely different songs. Or maybe like .cue (positions within a file), but subsongs have different channels/sample rate/etc.

- vgmstream has a massive list of supported extensions
Maybe VLC's plugins<>player extension passing isn't well developed as audio players and could cause issues.

- vgmstream uses external libs for some codecs that could clash with existing VLC libs
Using VLC's libs may be possible, but some like FFmpeg that change API/ABI while vgmstream expects certain versions.

Combined with the lack of interest I thought time was better spent elsewhere. Still you could ignore those issues/problem formats and just have a partially working vgmstream, though I'd think users would expect it to mostly work like other players.

**Comment by RQWorldblender** [comment]
Thank you for going into some technical details about VLC and vgmstream, it helped me realize that I was naive about their major differences that could make them conflict.
I guess I'll just convert soundtracks into WAV format with vgmstream-cli, and then play those with VLC, maybe convert them to other formats if I want to reduce their disk usage. Maybe one day I may come back to making a stripped down version of vgmstream as a VLC plugin as a side project, but that unlikely will be in the short term.
