### ISSUE TITLE
[Request] Decode KLZ files

### ISSUE THREAD

**Issue by lolcatw** [vgmstream/vgmstream#1485]
Hello, it's me again.

Corpse Party: Book of Shadows seems to be using the KLZ file format for menu interactions, background noises and other short sounds. VGMStream doesn't seem to be able to decode any of those files:

```
will@fuckedmachine:~/Downloads/iso/utils$ ./vgmstream-cli -o out.wav AFS\ Packer/bgl/WRONGEND.KLZ 
failed opening AFS Packer/bgl/WRONGEND.KLZ
```

I will be investigating this on my own accord, but any help would be appreciated. Here is the WRONGEND.KLZ file for your own analysis...

https://files.catbox.moe/uot37w.KLZ

Thanks again.

**Comment by lolcatw** [comment]
I just checked the file headers, it seems to refer to something called "TIM2", which seems to be an image file format.

Still looking for those menu sounds...

https://wiki.vg-resource.com/TIM2

**Comment by bnnm** [comment]
The file does not seem like audio to me. Maybe try looking for ADX or other less common CRI audio formats (such as .ACX) with tools like vgmtoolbox.

Since vgmstream just handles known/extracted files it's best to ask in ripping communities such as reshax or the xentax discord, as we can't really help you finding audio in bigfiles.

**Comment by lolcatw** [comment]
you're the best, thank you for the support
