### ISSUE TITLE
[Request] SNS files from Burnout Paradise

### ISSUE THREAD

**Issue by Darekptr** [vgmstream/vgmstream#1497]
The entire Sound>Streams catalog gave up. There are three examples in the ZIP.
[Uploading Sample.zip…]()

**Comment by applecuckoo** [comment]
@Darekptr The samples haven't been uploaded properly.

**Comment by Darekptr** [comment]
[Sample.zip](https://github.com/vgmstream/vgmstream/files/14411412/Sample.zip)

Sorry, first time using, also shitty internet. Here you go.

**Comment by bnnm** [comment]
.SNS are just data. You need to find .SNR which is the header. Those files are usually in .bndl, try extraction scripts such as those here: https://aluigi.altervista.org/quickbms.htm

Best ask in modding communities such as the reshax/xentax discord for support, since this is beyond vgmstream's realm.

**Comment by Darekptr** [comment]
OK, I thought that since a certain script from the Internet can convert .sns to .wave (but it is a slow process), the reason is the lack of support by vgm (specifically foobar2000 with the add-on). But thanks for the info and explanation.

Regards
