### ISSUE TITLE
[Request] Knack II (PS4) .bsxd

### ISSUE THREAD

**Issue by ColbyDash** [vgmstream/vgmstream#1499]
I couldn't find jack squat about this particular file format besides this [obscure forum post search for (marcusss' post towards the bottom of the page.)](https://hcs64.com/mboard/forum.php?showthread=8687&showpage=202) That and I have no idea if any other PS4 games use this one format or any platform in general for that matter. An archive featuring just (nearly) comprised of files of these can be found [here](https://archive.org/details/Knack2) for our purposes here though.

**Comment by bnnm** [comment]
All the files with `.b(something)` extensions seem to be a generic container for any data, and not an audio format that vgmstream could add. The files inside `.bsxd` are just `.sxd`, which are supported by vgmstream.

You can extract them by cutting with a hex editor up until the "SXDF" part then renaming the extension to `.sxd`. I don't know if a single `.bsxd` may have multiple subfiles though, so it may not be that easy for all cases.

Instead of manually doing that you can also unzip this TXTH file in the same folder as the .bsxd then play `(file).bsxd` directly (may need to set "allow unknown extensions" in vgmstream's options): [txth.zip](https://github.com/vgmstream/vgmstream/files/14422128/txth.zip)

**Comment by ColbyDash** [comment]
Thank you! Both methods works! (Duh but I am pretty happy they worked out because I was getting nowhere with another game's audio (compilation) files due to how little information there is about them as well.) Had to figure out how to get myself into the options configuration menu for VGM in the first place but once I had, it was smooth sailing from there. There are actually subfiles in some of the .bsxd's I've looked at through the automatic method you've listed. The most common of which are the ig labelled files, of which includes just conversations between various characters. Again, thanks for the piece of info! With that being said, I'll go ahead and close this request since I think we're pretty much done now, I am at least with my previous predicament. :D
