### ISSUE TITLE
[Request] Adding a option to repeat a file a set number of times to vgmstream123

### ISSUE THREAD

**Issue by KellenHurrey** [vgmstream/vgmstream#1532]
Like -r but allows to set the number of repeats. When I try to use python to run the files back-to-back, there is always a slight gap between when the first one stops and the second one continues. (I also have been struggling to compile vgmstream123 for windows for the last couple days, and am very stuck. If I could get some help with that, that would be great)

**Comment by bnnm** [comment]
I think what you really need is `-e` (or `-E`) and `-l (number)` to loop your file N times.

Here is vgmstream123 win32: https://github.com/bnnm/vgmstream-builds/raw/master/bin/vgmstream-latest-test-u.zip

**Comment by KellenHurrey** [comment]
Looks like its not doing it. Here is my console:
`PS C:\Users\kelle\python\SeaOfThievesSoundPlayer> .\AudioPlayers\vgmstream123.exe -e -l 4 AudioFiles\Txtp\7372950-0126-event.txtp
Audio device: WMM audio driver output
Comment: Outputs audio to the Windows MultiMedia driver.

Playing stream: AudioFiles\Txtp\7372950-0126-event.txtp
PS C:\Users\kelle\python\SeaOfThievesSoundPlayer> .\AudioPlayers\vgmstream123.exe -E -l 4 AudioFiles\Txtp\7372950-0126-event.txtp
Audio device: WMM audio driver output
Comment: Outputs audio to the Windows MultiMedia driver.

Playing stream: AudioFiles\Txtp\7372950-0126-event.txtp
PS C:\Users\kelle\python\SeaOfThievesSoundPlayer> .\AudioPlayers\vgmstream123.exe -l 4 -E AudioFiles\Txtp\7372950-0126-event.txtp
Audio device: WMM audio driver output
Comment: Outputs audio to the Windows MultiMedia driver.

Playing stream: AudioFiles\Txtp\7372950-0126-event.txtp
PS C:\Users\kelle\python\SeaOfThievesSoundPlayer> .\AudioPlayers\vgmstream123.exe -l 4 -e AudioFiles\Txtp\7372950-0126-event.txtp
Audio device: WMM audio driver output
Comment: Outputs audio to the Windows MultiMedia driver.

Playing stream: AudioFiles\Txtp\7372950-0126-event.txtp`

**Comment by bnnm** [comment]
I'd need that txtp since wwiser cases are particularly complex and may make vgmstream ignore those flags.

**Comment by KellenHurrey** [comment]
This is all that's in the file: `wem/276005375.wem #i`, other than comments.
The wem file it points to is correct, and I have thousands of these files, so I would rather not have to remove the `#i` flag from each line. Also, I have tried to run a basic test txtp, which called this file (or a similar one), with a `#l` flag, a `loop_mode = auto` line, and various other combinations.

**Comment by bnnm** [comment]
In this case `#i` inside the txtp has priority over `#e`, since it was mostly designed for people manually disabling loops for few files (meaning not looping should triumph over player's loop settings). I'll think a bit how to handle it.

Wwise typically sets precise loop config though, what kind of audio are those wem that needs to be forced to loop?
(also remember you can play the .wems directly without txtp, which should follow `#e`)

**Comment by KellenHurrey** [comment]
I see your point, and after going back to test my original file, I found that `-e -l #` must've been the only combination that I didn't try for my original txtp, because it works. However, I am writing a python script to play sounds using the txpts for a project (I have ~14k txtp files), and would like to be able to repeat a file, like with `-r`, a set number of times, for files that are like the one I mentioned above, in a way that is consistent with types of txtp files (like ones with `#i`, and ones without).

If I could figure out how to compile vgmstream123 for windows, I would attempt to make the change myself (I have very little c knowledge, but it seems like something I could do), but I am still struggling to do so.

**Comment by bnnm** [comment]
`-r` reparses the file, so `-e/E` would be more natural/faster (if they worked with that txtp here). While it'd be simple to add a repeat number option, feels like something that should be tweaked so that `-e` can handle.

For the time being I recommend simply repeating the input file N times (not just calling the program separately N times, to avoid pre-setup). Internally that's what `-r` does: `vgmstream123 blah.txtp blah.txtp blah.txtp ...`

As for compiling v123 if you can compile CLI with gcc/mingw it's the same, just you need to find/make libao dlls and includes though.
