### ISSUE TITLE
[Request] Read Loop Info for Some Switch Opus (Lopus) Files

### ISSUE THREAD

**Issue by Austin-Quick** [vgmstream/vgmstream#1536]
I'm not sure if this is better as a feature request or bug. When reading the opus files from the Switch version of Paper Mario: The Thousand-Year Door using VGMStream via Foobar, it does play the files correctly, but it does not contain any looping information. 

I know very little about this type of stuff, but I'm assuming the info might be in a slightly different place for these files than they are in other Nintendo Switch games?

I'm new to this, so what information do I need to share, and what's the best way to go about sharing it in order to get this feature implemented?

Thanks for your help!

**Comment by bnnm** [comment]
Most games use audio formats that define loop points inside its files. That is, you get looped/repeated audio in vgmstream simply by opening the files.

However some games use formats that don't define loops points, and instead store loops in the executable or some external file. For example they could have a bunch of `.ogg` and some .txt with start/end loop time info for all `.ogg`, or `.opus` files with loop samples defined in the `.bfsar`.

Since those cases are typically custom/per game, vgmstream can't really read those loop points automatically. Instead, one should make (with some tool or manually) one TXTP per file that tells vgmstream about its external loop points, and play the `.txtp`:
**BGM_BTL_ACMaster_opus.txtp**: `BGM_BTL_ACMaster_opus.lopus #I 258724 2929972`

Better ask in ripping communities such as hcs64 discord about those cases since it's beyond what we can do here.
