### ISSUE TITLE
[Bug] "Loop forever" failed on CUE sheet

### ISSUE THREAD

**Issue by ghf50** [vgmstream/vgmstream#1550]
Windows 11
foobar2000 v2.1.5 x64
vgmstream plugin r1917

"Loop forever" failed when using CUE sheet. I'm not sure if it is a bug.
Here is a CUE Sheet sample:

```
REM GENRE Game
REM DATE 2017
PERFORMER "Nintendo"
TITLE "Metroid Samus Returns"
FILE "m_prologue99.bcwav" WAVE
  TRACK 01 AUDIO
    TITLE "Prologue"  
    PERFORMER "Kenji Yamamoto"
    INDEX 01 00:00:00
FILE "m_select99.bcwav" WAVE
  TRACK 02 AUDIO
    TITLE "Menu"
    PERFORMER "Kenji Yamamoto & Daisuke Matsuoka"
    INDEX 01 00:00:00
```

**Comment by bnnm** [comment]
CUEs are handled by foobar externally so can't do much about it.

Seems they force songs to stop after the reported length, rather than keep playing if the plugin can go on, due to how BIN+CUEs work I guess. Since this is for single files maybe foobar's authors can fix it.

If you are using CUEs just for tagging maybe you could use [!tags.m3u](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#tagging) instead, which would allow looping forever.

**Comment by ghf50** [comment]
Thank you, bnnm.
Yes, I'm using CUEs just for tagging them. use !tags.m3u maybe a good option.
