### ISSUE TITLE
[Bug] `.txth body_file` absolute path

### ISSUE THREAD

**Issue by Razmoth** [vgmstream/vgmstream#1553]
Greetings,

As the subject suggest, `body_file` seems to only accept relative path to be specified in order for `.txth` file to be loaded properly.

Example:
`1.txth` in `C:\Users\XXXX` with `body_file = .\Desktop\audio.gpk` = works
`2.txth` in `D:\Audio` with `body_file = C:\Users\XXXX\Desktop\audio.gpk` = doesn't work.

**Comment by bnnm** [comment]
I've relaxed some checks so those paths may or may not work in your case, but basically only relative paths are officially supported since can't really unify all plugins/OSs.

Different plugins handle paths differently so typically only relative paths can be handled easily/consistently. For example foobar2000 uses custom uri-like paths and absolute paths like C:\blah\... won't work (afaik), while CLI/v123 may works ok (on Windows, but not Linux).

**Comment by Razmoth** [comment]
Greetings,

Thanks a lot, working well now (tested on windows only)
