### ISSUE TITLE
[Bug] Some of the sub-song names don't look right

### ISSUE THREAD

**Issue by MatchaCabin** [vgmstream/vgmstream#1562]
[VO_Centaureissi_JP.zip](https://github.com/user-attachments/files/16339181/VO_Centaureissi_JP.zip)
Sample from Girls' Frontline 2: Exilium

`vgmstream-cli -m ./VO_Centaureissi_JP.acb -s 20`
> metadata for ./VO_Centaureissi_JP.acb
sample rate: 48000 Hz
channels: 1
channel mask: 0x4 / FC
stream total samples: 4240 (0:00.088 seconds)
encoding: CRI HCA
layout: flat
metadata from: CRI HCA header
bitrate: 165 kbps
stream count: 70
stream index: 20
stream name: VO_Centaureissi_Series_Battle_Start [pre]; VO_Centaureissi_Series_Move_Start [pre]; VO_Centaureissi_Series_Set_Click [pre]; VO_Centaureissi_Series_Tone_Positive_006 [pre]
play duration: 4240 samples (0:00.088 seconds)

I get a lot of weird filenames when trying to export sub-songs.
There seems to be some other stream names mixed in.
In fact, only the last part is the real name.
I uploaded a sample for you.
Is this a bug?

**Comment by bnnm** [comment]
What you see should be correct. That's because .acb don't have *filenames*, but *cue names*.

Multiple *cue names* can point to the same HCA, so vgmstream simply shows all possible names separated by `;`.

Typically 1 subsong will have 1 cue name, but sometimes 1 subsong has many cue names (like `VO_Centaureissi_Battle_Start` and `VO_Centaureissi_Move_Start`), or 1 *cue name* has many subsongs (like `VO_Centaureissi_Series_Hitted`).

In this case it looks `VO_Centaureissi_Tone_Positive_006` is "correct" because it's more unique, but vgmstream can't really tell them apart. 

For example, subsong 59 has 2 cue names (`VO_Centaureissi_Series_Shield_Broken; VO_Centaureissi_Single_Kill_001`) and both look unique enough to me.

**Comment by modusc896d352** [comment]
yo, @MatchaCabin, how do you know that the last part is the real name?

**Comment by MatchaCabin** [comment]
> What you see should be correct. That's because .acb don't have _filenames_, but _cue names_.你看到的应该是正确的。那是因为 .acb 没有文件名，而是提示名称。
> 
> Multiple _cue names_ can point to the same HCA, so vgmstream simply shows all possible names separated by `;`.多个提示名称可以指向同一 HCA，因此 vgmstream 仅显示用 `;` 分隔的所有可能名称。
> 
> Typically 1 subsong will have 1 cue name, but sometimes 1 subsong has many cue names (like `VO_Centaureissi_Battle_Start` and `VO_Centaureissi_Move_Start`), or 1 _cue name_ has many subsongs (like `VO_Centaureissi_Series_Hitted`).通常 1 个子歌曲有 1 个提示名称，但有时 1 个子歌曲有许多提示名称（如 `VO_Centaureissi_Battle_Start` 和 `VO_Centaureissi_Move_Start` ），或者 1 个提示名称有许多子歌曲（如 `VO_Centaureissi_Series_Hitted` ）。
> 
> In this case it looks `VO_Centaureissi_Tone_Positive_006` is "correct" because it's more unique, but vgmstream can't really tell them apart.在这种情况下，它看起来 `VO_Centaureissi_Tone_Positive_006` 是“正确的”，因为它更独特，但 vgmstream 无法真正区分它们。
> 
> For example, subsong 59 has 2 cue names (`VO_Centaureissi_Series_Shield_Broken; VO_Centaureissi_Single_Kill_001`) and both look unique enough to me.例如，子歌 59 有 2 个提示名称 （ `VO_Centaureissi_Series_Shield_Broken; VO_Centaureissi_Single_Kill_001` ），对我来说两者都足够独特。

Thanks for the answer, I understand now!
That means multiple names could point to the same subsong, and multiple subsongs could have the same name.
Maybe it's just a game maker setting error?

**Comment by MatchaCabin** [comment]
> yo, @MatchaCabin, how do you know that the last part is the real name?

![QQ_1721715236319](https://github.com/user-attachments/assets/783963c7-0013-4ec9-91a5-cb654677b1e9)
[VO_Dusevnjy_JP.zip](https://github.com/user-attachments/files/16344470/VO_Dusevnjy_JP.zip)

Most of the other files were fine, so I thought it was a parsing error before

**Comment by modusc896d352** [comment]
huh...

**Comment by bnnm** [comment]
> Thanks for the answer, I understand now!
That means multiple names could point to the same subsong, and multiple subsongs could have the same name.
Maybe it's just a game maker setting error?

A common case is games using one *cue name* to call a random subsong. That's why there are several subsongs with the name `VO_Centaureissi_Series_Hitted`: game uses that *cue name*, and 1 of several "hit voice " subsongs will randomly play (the group is classified in .acb as a "random" type).

`VO_Dusevny_JP` doesn't have `*_Series_Hitted` so maybe it's not used in gameplay like `VO_Centaureissi_JP` is, so it has less names I guess.

Rarely vgmstream can't show some cue names due to bugs, but I think it's correct here.
