### ISSUE TITLE
[Request] Crash Tag Team Racing (PS2/PSP/NGC/Xbox) .rsd file

### ISSUE THREAD

**Issue by LuckyMage92** [vgmstream/vgmstream#1563]
Please add the support of the .rsd files and its subsongs.
https://mega.nz/file/ZHY3iBRL#gVEo5MYIP6eWAMqJ3CYhYho3Nvo2lXuHTYMCGh4qTVQ

**Comment by modusc896d352** [comment]
i had to check these files against latest (nightly) vgmstream build (r1917-144-gae167795 btw). these "RSD6VAG" files you posted do not have any subsongs.

**Comment by LuckyMage92** [comment]
Well, they DO have subsongs. But it happens after they got converted to any audio files. Is that a bug or something?

**Comment by modusc896d352** [comment]
no. if (say) eefa30b273cc92be.rsd got converted to eefa30b273cc92be.wav then that's all you get.
same with c7318b21b02babde.rsd, ab01ba3ec2807917.rsd, and so on and so forth.

**Comment by LuckyMage92** [comment]
Here's the proof. 
![AAAAA 25_07_2024 19_45_43](https://github.com/user-attachments/assets/bbef6b0d-c854-4401-8720-d001e5db7528)

**Comment by bnnm** [comment]
Not sure what you mean by "subsongs popped out". Those names are just the internal stream_names each .rds has. But .rsd can only have one song per file (having a name doesn't mean format has subsongs).

If you mean that the stream_name doesn't show in the playlist, by default vgmstream doesn't use it for formats with only 1 song like .rsd, since they often have bogus names. You can change that: [info](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#default-title-and-playlist-columns)

**Comment by LuckyMage92** [comment]
I see. Will keep that in mind. Thank you.
