### ISSUE TITLE
Attempt to implement clang-format rules

### ISSUE THREAD

**Issue by kode54** [vgmstream/vgmstream#157]
@bxaimc / @bnnm 
We need to find a way to get clang-format to work on this code base. I found that it sort of works, but it mangles comments, and it will add new levels of mangling every time it processes a file.

Stuff like this:

```
#define MACRO \
    4 /* something something \
        */
```

Will happily get mutated into:

```
#define MACRO                                                    \
   4 /* something something \                               \
          \                                                                 \
       */
```

And it will add more lines full of backslashes each time it processes the file, making the comments bigger. Perhaps a bug in the Win32 snapshot I picked up today?

At the very least, try turning your tabs off when formatting files for VGMStream. If we can help it, we should be using 4 spaces, no tabs, everywhere. I see this has not been followed for years, and there are messes of tabs everywhere.

**Comment by bnnm** [comment]
I'll take a look later as I'm not very familiar with code formatters. Given the low amount of contributors I don't think it matters that much though. Maybe we could propose a suggested set of guidelines but I'd keep the entry bar low.

I try to remove tabs and tweak minor things near stuff I touch for consistency, but maybe what I find consistent others think is strange (for the record I don't have that much experience with C either, perhaps I do unusual things at times). Should I make a list of my suggestions?

**Comment by kode54** [comment]
Sure, that would be great. And no, I don't want to scare anyone off, least of all either you or bxaimc.

**Comment by bnnm** [comment]
Style and other considerations I try to follow:
- 4 spaces instead of tabs
- underscore_and_lowercase_names instead of CamelCase
- /* C89 comments */ for descriptions/info/etc, //C99 comments for special/extra/to-be-revised stuff (ex. I may leave "//do_stuff()" to remind me I didn't do_stuff() for a reason)
- bracket start in the same line (if (..) { CRLF ... })
- line length 100-120, less is limiting, more is ok for 'noise code' (ex. uninteresting calcs or function defs)
- offsets/sizes in hex, counts/numbers in decimal
- in functions I like returning 1=ok, 0=ko for simplicity.
- free(ptr) no need to NULL-check per standard, close_stuff(ptr) should also follow this
- filenames_underscore_and_lowercase. Suffixes for related/helper files.
ex. seeing all those x_blocked.c layouts was head-scratching at first, I think as blocked_x.c it's a lot clearer they are variations of the same thing.
- lowercase_helper_structs, UPPERCASE_MAIN_STRUCTS
- add spaces in calcs/ifs/etc when feels clearer
ex. "if (simple_check)" vs "if ( complex_and_important_stuff(weird + weird) )"
- extra CRLF to separate sections when feels clearer
- I tend to over-comment a bit as I easily forget why/what, plus to 'read aloud' and catch logic bugs, no need to follow this. Hard for me to be concise in English though (I realize they aren't well written but oh well).
But for odd fixes or uncommon cases I hope people write some affected game, to test future changes.
- when touching other people's code I somewhat keep the style, but may adapt if I need to change/mantain or understand large chunks
- some code repetition is ok if done for clarity or to simplify, not cool if just habit (like those copypasted "open streamfile" sections at the end of metas)
- 1 meta file per format (sub-formats/versions can go inside too), named after the extension. Try to parse fields in header order (descriptive). Favor clarity even with some repetition (ex. wwise.c is an almost-RIFF header, but rather than put in riff.c a bunch of hacks I separated)
- complex init/free/etc should be on its own file when possible

Generally I try to follow C conventions, or styles I already found in vgmstream, but as I said I'm not that experienced with C. I don't always follow closely, or may attempt different things to see if it works better, etc. As long I there is some internal consistency within functions works for me.


Also, possible future changes:
- cleaner structure (not too happy how streamfile.c, coding_utils.c and stuff have a bunch of random functions, need to rethink)
- external/DLL API and cleaner internals (other projects could benefit)
- simplify layouts and unusual/rarely used features (very confusing when I started contributing)
- standardize/simplify STREAMFILEs (ie. I noticed there is a decrypting STREAMFILE that could be reused)
- simplify some decoders (ex. my custom FFmpeg I/O codecs would be cleaner with STREAMFILEs, but I don't quite get them yet)
- I'm debating about adding a frame_size field (for MSADPCM, MS-IMA, etc). Right now interleave_block_size is reused, and while variable-sized codecs with interleaved channels are rare, I think would be cleaner (took me a bit to follow, when trying to learn how codecs+layouts worked)
Some of my code is how it is due to my own limitations rather than choice, I guess I'll keep improving.

I want to expand my BUILD doc with more dev info, could add suggested guidelines. Its mostly self-reminders but maybe would lower the entry bar for others (can't contribute forever...).
