### ISSUE TITLE
[Request] Taiko no Tatsujin: Rhythm Festival PC (Demo) Audio

### ISSUE THREAD

**Issue by cainan-c** [vgmstream/vgmstream#1585]
A demo recently released for the PC port of this Taiko no Tatsujin game, this game runs on Unity and appears to be using HCA audio just like it's Switch counterpart. However, seemingly using a new key? Either that, or the HCA file itself is different, as it's unable to play/decode using VGMStream

Here is a single sample audio file from the game
https://drive.google.com/file/d/1K34tZVeXL4WiB7F-zmfrwcdfOEOcjZkb/view?usp=drive_link
It is a pre-decrypted version of SONG_SW2OP 
And a link to the Steam page for the game and it's demo: https://store.steampowered.com/app/2288630/Taiko_no_Tatsujin_Rhythm_Festival/

If any more sample files are needed, please let me know

**Comment by bnnm** [comment]
I couldn't access the link since it asks for permission, but I tried decrypting a song `.bin` from the demo with [your tool](https://github.com/cainan-c/tns2tool) and seems it results in a padded file.

The correct size of a `.acb` is `(BE value at offset 0x04) + 0x08`, if you remove the excess data it plays ok (same hca key as the switch version).
