### ISSUE TITLE
[Request] Beowulf: The Game (bao files)

### ISSUE THREAD

**Issue by leop2p** [vgmstream/vgmstream#1637]
Hi!

Could you add support for these bao files to play through vgmstream?

Thanks!!!

https://mega.nz/file/q59XVB6A#pBQMHkXhsrStnrD2hYFatgYQWKQ-wSrzQBkHOLmB8CQ

**Comment by leop2p** [comment]
Need help. When I use scimitar_forge_compressed_bao.bms on for example extracted "Common_BAO_0x0000a0cb" (extracted without extension) it says "Couldn't not find compressed ID"

**Comment by bnnm** [comment]
You need to use scimitar_forge.bms to get .compressed files, then scimitar_forge_compressed_bao.bms to extract the .compressed files that extracts. If you already have files like `(Common_)BAO_0x3xxxxxxx` those are fine too.

Note I don't know if Beowulf's "header BAOs" are inside .forge, those are examples for similar games. Maybe BAOs in your case in some sound.bin or something. Either way, you need to find and extract those files for vgmstream.

Since this repository only deals with extracted game audio, but not with extraction itself, best ask in ripping communities such as the xentax discord or reshax since we can't really help you much else.

**Comment by leop2p** [comment]
> You need to use scimitar_forge.bms to get .compressed files
But files are extracted without extension, and when I trying `scimitar_forge_compressed_bao.bms` script on those files it gives me an error `Couldn't not find compressed ID`. I used script for `Prince of Persia: The Forgotten Sands` and have set up the script for that game. What does that error mean? What should I do?

**Comment by bnnm** [comment]
If files are extracted without extension, it means they are not compressed. If they are not compressed it means you can't use `scimitar_forge_compressed_bao.bms`, and if and you don't have files like Common_BAO_xxxxxxx it means BAOs are not in `.forge`.

Probably they are in sound.bin/fat. No idea how to extract it, already explained where you should ask.

**Comment by leop2p** [comment]
There's no **`.forge`** files. There's only **`yeti.big`** file with idstring **_"V"_**
