### ISSUE TITLE
[Request] Allow the CLI to take input from stdio

### ISSUE THREAD

**Issue by ryi3r** [vgmstream/vgmstream#1639]
When starting the CLI tool as a process from a coding language, you (almost) always get the option to send data to stdin, the same way the program can also send decoded data to stdout.
This could be useful if the code launching vgmstream manipulates the data to be readable from vgmstream (say, a compressed file or something), and then read it back, stdin could remove the abstraction of writing to a file.

This could work in the following way:
`-n` tells vgmstream to expect data not from a file, but from stdin.
and/or, you could specify the data size to be expected:
`-n <data_size>`
As an example, this could be used as such:
`vgmstream -i -p -n 1024`

**Comment by bnnm** [comment]
While it's probably doable this seems of rather limited use, and the less features/corner cases for vgmstream the better for scope/maintenance.

vgmstream sometimes needs to seek headers at the end of a file or open companion files. Meaning, you would need to pass and keep the whole file in memory and not all cases would work anyway. At that point I think dumping stdin to file + run vgmstream + delete dump is a clunky but more flexible replacement.

**Comment by bnnm** [comment]
No further comments so closing.

**Comment by bnnm** [comment]
It's technically possible what you mention, and ignore edge cases, but the use case is still not clear to me.

In other words, vgmstream plays existing game audio files, so piping from another program is an anomaly. An explanation of why/when/how you want to do this would be more useful to consider adding. (do you need to solve some particular issue? is all this theoretical? etc)

**Comment by ryi3r** [comment]
The intention of this feature is to allow code to convert different kinds of audio without any kind of bindings (through the cli?)
While this is a audio playback library, it can also be used to convert audio through cli instead, adding piping to this would allow faster execution times for this usage case (less system calls to save the audio into a file and reading it back, or something of these sorts.)

**Comment by bnnm** [comment]
It's clear what you want and the theoretical benefits. Rather, I'm asking: do you have some program calling vgmstream and it's slow or something, what is it actually trying to do? By understanding actual use cases I can give you alternatives or raise less obvious issues.

For example, let's say your program needs to convert 10000 files calling vgmstream file by file. It may seem that the tmp file itself is slow (it is, somewhat), but actually calling `vgmstream file1`, `vgmstream file2`, `vgmstream file3` ... is slower than `vgmstream file1 file2 file3 ...` due to program initialization stuff. Maybe even after adding piping (single file by nature) it'll be still a lot slower than the second option with N tmp files.

Further, one usually doesn't convert 10000 files to wav all the time. Maybe I'll have to put +10 hours of work + maintain it every time I fiddle with the CLI code, for something that only saves 30 minutes of people's time once. I would rather use those 10h for more impactful like a new codec. But since I don't know the use case it's hard to gauge.

Going by your github perhaps you have a player and want to play some .wem in an archive or such. Maybe a more workable solution would be telling vgmstream the archive and offset+size of the internal file, since that code exists internally (plus you wouldn't have to read/pipe anything yourself). One user did a hack using `.txth` files to tell vgmstream the internal files [here](https://github.com/RazTools/Audio) too. Or maybe you don't really need the .wav and just want to *listen* to audio from your program, so actually adding this feature to vgmstream123 (CLI player) would be more useful. etc.

**Comment by ryi3r** [comment]
I see. I think telling vgmstream offset+size would be a good approach, being able to input it multiple times (like you showed here converting multiple files at the same time.)
I'll take a look into the hack and see if I can use it.

**Comment by ShadelessFox** [comment]
I want to extend on that. Here's my use case: I want to convert in-game ATRAC9 audio to a format that my program understands. The game stores data in compressed archives, and I unpack files in memory on demand. I want to be able to pump the unpacked audio file directly into vgmstream without creating any temporary files, and redirect its output back to my program for playback or other purposes.

**Comment by ryi3r** [comment]
Hi, the solution I ended up using was using the WASM version of vgmstream and recreating the functions it needed ~~while trying to read the javascript code that came with it~~, needless to say I think it works pretty well, there could be bugs, though.

**Comment by ShadelessFox** [comment]
I decided to try my best and see what I could do with vgmstream's source code, and I didn't get far :^) vgmstream performs numerous file operations that are not quite possible with pipes (`stdin` in the question, notably, seeking and telling). It did produce a WAV file, but the actual data, besides the header, was just zeroes. I'll try my luck with libatrac9, which vgmstream itself uses.
