### ISSUE TITLE
Lego Lord of the Rings .CBX file

### ISSUE THREAD

**Issue by Xehanort88** [vgmstream/vgmstream#197]
Hello,
in theory this is supposed to be VO. But in practice I can't get it to work with any programme that I know of. Please, could you have a look at it?

[vo_tombombadil_singing1.zip](https://github.com/kode54/vgmstream/files/1745740/vo_tombombadil_singing1.zip)

**Comment by bnnm** [comment]
It has a header, but I don't recognize the codec.
You could post the exe and dlls, probably they have hints.

**Comment by Xehanort88** [comment]
Thank you, I'll try to get a hold of 'em.

**Comment by Xehanort88** [comment]
[LEGO® The Lord of the Rings™.zip](https://github.com/kode54/vgmstream/files/1754183/LEGO.The.Lord.of.the.Rings.zip)
There we go.

**Comment by bnnm** [comment]
Unfortunately didn't see anything particularly interesting. The file seems too small to be PCM/ADPCM, and doesn't look like MP3/OGG/etc either.

It could be that its a speech codec (but nothing in the exe suggests that), or maybe part of the file is compressed (0x00 is the header id, 0x04 could be total samples or uncompressed size, 0x08 is sample rate and 0x0c+ the data I believe). Either way I don't think I can figure out anything more, the guys at zenhax may know if its compressed.

**Comment by bxaimc** [comment]
What console is this from btw?

**Comment by Xehanort88** [comment]
PC actually.

**Comment by SirYodaJedi** [comment]
If anyone needs help verifying their results when decoding CBX files, Lego The Hobbit has uncompressed WAV duplicates of almost all of its CBX files. [I attached a voice clip of Gandalf laughing as an example](https://github.com/vgmstream/vgmstream/files/7908483/VO_GANDALF_LAUGH_01.zip).

On a minor note, CBX stands for "ChatterBoX", as I found this sting at offset 0xDBC1E4 of the [Lego Marvel 1 PC demo executable](https://github.com/vgmstream/vgmstream/files/7908487/LEGOMarvelDemo.zip) (and those of several other games on the same engine): 
```
57 61 76 65 20 66 69 6C 65 73 20 28 2A 2E 77 61 76 29 7C 2A 2E 77 61 76 7C 43 68 61 74 74 65 72 62 6F 78 20 66 69 6C 65 73 20 28 2A 2E 63 62 78 29 7C 2A 2E 63 62 78
```
Which HxD decodes as:
```
Wave files (*.wav)|*.wav|Chatterbox files (*.cbx)|*.cbx
```

**Comment by applecuckoo** [comment]
@connorh315 has created a [CBX Decoder](https://github.com/connorh315/CBXDecoder/tree/master) in C#. I'm not sure if he'd be open to porting it to vgmstream or making a write up on the format.

**Comment by bnnm** [comment]
That's useful, thanks. On a quick look seems correct and mostly the same as decompiled code found like "NuSoundDecoderCBX" in exes with some debug symbols (like LegoMarvel). Could use it as a base for vgmstream but needs some cleanup. iirc it's a simple dct-like codec but decompiled code unrolls loops and stuff that needs a bit more reverse engineering.

(main reason it's still wip is that it's just used for voices and I don't think there is much interest)

**Comment by connorh315** [comment]
> That's useful, thanks. On a quick look seems correct and mostly the same as decompiled code found like "NuSoundDecoderCBX" in exes with some debug symbols (like LegoMarvel). Could use it as a base for vgmstream but needs some cleanup. iirc it's a simple dct-like codec with bitreading/etc but decompiled code unrolls loops and stuff that needs a bit more reverse engineering.
> 
> (main reason it's still wip is that it's just used for voices and I don't think there is much interest)

WHAT! I didn't know LegoMarvel had debug symbols... Looks like I wasted a lot of time then.

Feel free to use what I've produced if it is of any use. It works for about 99% of the files, I've only been sent 1 file that the decoder failed to work on.

**Comment by bnnm** [comment]
Oh, I just meant LegoMarvel has a some names like vtables/classes (rather than full debug symbols inside functions), nothing big but helps a lot with finding the decoder since other Lego exes strip names. Lego Star Wars switch also has most function names, nice but also wouldn't really help that much (main decoder class is `nttAudioHAL::SourceDecoderCBX::DecodeNextFrame` that calls `CBOX_Decode`, which is `SeekThrough` in your code). Sound lib seems to be called "NuSound" also.

 Anyway thanks a lot for your decoder, it's much easier having something confirmed to work as a base rather than wip decompiled code.

**Comment by bnnm** [comment]
Added, it was indeed a speech codec.

***

After poking some more at the decompilation and code by connorh315 (thanks again), the tables and numbers started to seem familiar. Turns out this codec is EA's MicroTalk (MT), just with fixed config. The only link between EA and Traveller's Tales I could find is David Whittaker who worked for a few years at EA doing voice related stuff before going to TT to also work on voice stuff. MT was his parting gift I guess.

Anyway, MT was already supported by vgmstream, so it just needed some tweaks.

***

For potential modders there is actually a public MT encoder: [utkencode.c](https://github.com/daddesio/utkencode/blob/master/utkencode.c). If somebody is interested in making a .cbx encoder I think this would work (probably):
- change lines 985~994 to write a CBX header instead: "!B0X" + pcm size + sample rate
- comment out lines 1000~1005 (MT bitheader, not used in CBX)
- compile (may need linux's getopt.h, on windows you can use vgmstream's in ext_libs)
- encode with defaults (-H -T 24 -S 64 -B 1.068) as CBX can only use those. bitrate may be ok to change?

**Comment by Sajjadsa1381** [comment]
> That's useful, thanks. On a quick look seems correct and mostly the same as decompiled code found like "NuSoundDecoderCBX" in exes with some debug symbols (like LegoMarvel). Could use it as a base for vgmstream but needs some cleanup. iirc it's a simple dct-like codec with bitreading/etc but decompiled code unrolls loops and stuff that needs a bit more reverse engineering.
> 
> (main reason it's still wip is that it's just used for voices and I don't think there is much interest)


> Added, it was indeed a speech codec.
> 
> After poking some more at the decompilation and code by connorh315 (thanks again), the tables and numbers started to seem familiar. Turns out this codec is EA's MicroTalk (MT), just with fixed config. The only link between EA and Traveller's Tales I could find is David Whittaker who worked for a few years at EA doing voice related stuff before going to TT to also work on voice stuff. MT was his parting gift I guess.
> 
> Anyway, MT was already supported by vgmstream, so it just needed some tweaks.
> 
> EDIT: found that another minor variation of .cbx as .box can be found in Warthog Games' Looney Tunes: Back in Action Animaniacs: The Great Edgar Hunt (GC) (not other platforms or earlier Warthog Games I think). Some Warthog staff later went to work on Lego games for [TT](https://www.mobygames.com/company/12637/tt-fusion-ltd/). How curious.
> 
> For potential modders there is actually a public MT encoder: [utkencode.c](https://github.com/daddesio/utkencode/blob/master/utkencode.c). If somebody is interested in making a .cbx encoder I think this would work (probably):
> 
> * change lines 985~994 to write a CBX header instead: "!B0X" + pcm size + sample rate
> * comment out lines 1000~1005 (MT bitheader, not used in CBX)
> * compile (may need linux's getopt.h, on windows you can use vgmstream's in ext_libs)
> * encode with defaults (-H -T 24 -S 64 -B 1.068) as CBX can only use those. bitrate may be ok to change?

Hello friend, what's up.. Can you guide me exactly for this task?! I want to convert some of my .wav files to .cbx and I need to do this. I've changed the lines and also did the things you said, but it's not coming out right.. Could you please compile it for me and send it?! I would really appreciate it.
