### ISSUE TITLE
How hard is it to convert switch lopus files to standard ogg opus files?

### ISSUE THREAD

**Issue by wildsalarian** [vgmstream/vgmstream#342]
If I understand it correctly, Switch lopus files are using a custom container format instead of ogg, which is a widely used standard for opus files. For decoding, vgmstream creates an ogg-header and translates the lopus chunks into ogg pages. The results are fed into ffmpeg via callbacks. 

I tried to simply fwrite the buffers, which where forwarded in the ffmpeg callback into a file. The result was a valid opus file, which could be played in rhythmbox and audacious without the vgmstream plugin, BUT the different parts of the loop were scrambled. Wrong parts of the song spontaneously started playing where the should not. So it seems that there are some deeper complexities in the looping feature, which I do not fully understand.

How hard would it be to add such a feature? It would be quite nice, since the song would still be compressed (in contrast to a wav file) but no quality would be lost (in comparison to re-encoding the generated wav file afterwards) and yet it would be playable with many audio players out of the box, especially for us linux people. (Winamp installation on windows is just copying a bunch of DLL-Files, but compiling the audacious plugin on linux with opus support is not that easy)

**Comment by bnnm** [comment]
I find that kind of transmogrified data reprehensible, so I'm afraid I would never add such feature.

You are free to tinker with the code though. You could disable looping to create a base ogg, then externally recreate loops by finding loop sample page, then appending that loop section. vgmstream can't help with this due how it loops internally, plus I don't think you can create a 100% accurate pre-looped file anyway, as ogg page samples are 'aligned' while loops are not. Also do note this internal ogg was just a quick hack that creates very unoptimized oggs.

Instead I suggest getting somebody with enough knowledge to make audacious+ffmpeg possible, which would benefit everybody with many formats, not just Switch Opus.

**Comment by kode54** [comment]
There are already scripts in the Arch User Repository for building the Audacious plugin with FFmpeg support. In fact, the only things missing from vgmstream-kode54-git are G.719 and the reference G.722.1 decoder. The maintainer of that AUR package didn't want to incorporate libraries that had questionable license status, and suggested that your G.722.1 GitHub account may not be legal, license wise.

**Comment by bnnm** [comment]
I looked into that AUR before but I understand it's using a custom aur script so that limits usage I think. Since I don't know that much about scripting plus I test Linux stuff in an ungodly slow VM it's quite hard for me to improve the situation, but it could be used as a base for other scripts.

My G.722.1 definitely may not be legal (also pointed [here](https://github.com/losnoco/vgmstream/blob/master/doc/BUILD.md#libg7221_decode)), but note that [libsiren](https://github.com/kode54/libg7221_decode) is 100% a clone of Polycom's ref code (I guarantee) with all references to Polycom removed, which is worse I think, so I guess Arch mantainers should remove it too.

Ideally some day we'll reverse engineer Namco's BNSF implementation, which I suspect is quite simplified since they got it running in the NDS and all, and there is a variation that isn't supported.
