### ISSUE TITLE
let's discuss vgmstream's bogus xsb handling

### ISSUE THREAD

**Issue by RetingencyPlan** [vgmstream/vgmstream#502]
okay, so xsb support is there on vgmstream. however, the way it's done is, as said in the title, completely bogus.

the xsb format that is (somewhat) part of the whole XACT audio middleware system in the first place was designed with (for all intents and purposes) the idea that there should be at least _one_ file acting as the middle ground for all existing fellow xwb files (which contain their own set of actual sound data), not only providing extra information for said xwb files but also serving as the de-facto sound engine for DAW-like features. although most games that use this middleware seem to use it as a simple audio bank.

however (although xsb files can be quite complex) the way vgmsteam handles it is that a xsb file must be either with a corresponding xwb file so vgmstream can parse the necessary xsb data into the corresponding xwb file that has the same name as the xsb file [with few exceptions...](https://github.com/losnoco/vgmstream/blob/master/src/meta/xwb_xsb.h#L726) this part of code here is especially upsetting to me because the code has everything it needs for this xsb format to be handled on its own without having to drag an fellow xwb file into it, hence the point of this new issue. and yes i know there are games out there that treat the xwb and xsb files as if they're supposed to be a pair of xwb+xsb files(Xbox version of **_Headhunter Redemption_** is a perfect example of this in action), but there are other games out there that use the xsb file as a completely different entity that provides some info for other xwb files(Xbox version of **_Crouching Tiger, Hidden Dragon_** has one xsb file and five xwb files for everything else, Xbox version of **_Psychonauts_** does this as well except the xwb and xsb files are organized so that they're separate from each other, thus the reason you see "XACT Soundbanks" and "XACT Wavebanks" in the "Sounds" folder of that version of the game. this one case in particular needs some sort of special handling for this to work.)

here's a file i managed to get from some 2003 multiplat game that i mentioned earlier.
[[crouching_tiger_hidden_dragon_xbox]bank_xsb.zip](https://www.sendspace.com/file/6cp8xy)
this file contains two string sections:
1. name of the xwb files that the xsb file is tied into
2. name of whichever sound entry that is stored in either one of those xwb files

the first section should have exactly what vgmstream needs in order to load xwb files through the xsb file itself. the rest should be fairly "easy" to follow.

so, i'd say that vgmstream should handle xwb and xsb files completely independently so as to present a choice to the user. if a xwb file has a xsb file of the same name and the xsb file has something that indicates that it needs just one xwb file to load, okay. if it doesn't, that's okay too, since if the user wants to play a bunch of sounds with names in them xe can just load the .xsb file just fine or if the user is not too picky about names then xe can just load the .xwb as well. i do want vgmstream to handle xwb and xsb as two separate formats though, as xsb can load xwb files by itself just file.

**Comment by bnnm** [comment]
Parsing "cue" formats like .xsb, .acb, .sgh, etc as a format is hopeless because:
- they are terribly complex and very hard to get them right (*enormously* more complex than almost every vgmstream format)
- it's far easier to load the bank and just try to read names from the cues (if parsing is wrong you simply don't get names)
- often little documented, so basically I have to figure them from zero by putting many, many hours
- almost nobody wants to play cues instead of banks, so those many hours to figure them out would be better used to get other formats/codecs/features added
- xsb code may look complete but it's not, it could only play simpler xsb. I'd have to waste time by repurposing code to count subsongs and load banks and parse certain banks subsong only and stuff
- cues have many features that are useless for regular, pleasant VGM listening, like:
  - many cues that play the same sound
  - cues with configuration only that don't point to a sound
  - cues that are the same sound with different volume/tempo/etc
  - cues that give random sound 
  - etc
- sometimes sounds in banks don't get referenced by any cue, so you can't hear everything with the xsb alone
- it needlessly confuses people: open .xwb you get all possible songs in order, open .xsb and you get... songs in some other order, repeated, with other pitch?
- while .xsb happens to have bank names, other cue+bank formats don't and devs are free to load whatever pair they want
- if I "just" add xsb cues ultimately I'd get asked "add this other cue format too"

Therefore there is very little chance of this happening. The only cue format I see worth adding could be Wwise .bnk since it contains loops, but it's also very complex.

**Comment by AnonBaiter** [comment]
okay, i'm sorta speechless there. sorry about all that.
forgive me if this question is unrelated in some way, but do you still want me to keep this issue open for... something contribute that might happen with this github issue in the future?

**Comment by bnnm** [comment]
I don't think there is anything to be done here, given the arguments against it.
Mind you, I don't like the xwb<>xsb filename_pairs list in the code either, but it's the lesser evil here.
