### ISSUE TITLE
(Request) Assault Lily Last Bullet (Android) .awb & .acb support

### ISSUE THREAD

**Issue by Mysticus92** [vgmstream/vgmstream#800]
Please, add these .awb & .acb files for vgmstream from the game called Assault Lily Last Bullet.
[Common.zip](https://github.com/vgmstream/vgmstream/files/5841258/Common.zip)

**Comment by bnnm** [comment]
Added key

**Comment by gbf-dtb** [comment]
They seem to be using different keys for different .ADX files, current ADX key works for just bgm_anime_10.

bgm_anime_19:
62550609345 / 0000000E904E8DC1

bgm_anime_31:
295705462541 / 00000044D96B470D

bgm_anime_36:
153149523965 / 00000023A86C47FD

bgm_anime_40:
31169875891 / 0000000741DE8FB3

bgm_anime_42:
552857339257 / 00000080B8DD8579

bgm_anime_52:
1021673522249 // 000000EDE07CC449

bgm_outsource_11:
109554813891 / 0000001981F9CBC3

The theme songs (other than OP) are all in a different folder downloaded after the tutorial, have no idea how to find the original file names for them.

Slightly off-topic question, how do we add multiple keys into one .adxkey file (or is it even possible)?

**Comment by bnnm** [comment]
They should be playable now if you open the original .awb directly.

Each .awb has a sub-key value mixed with a base key, that is now handled automatically by vgmstream. If you extract .adx from .awb then you'll have to make a .adxkey per file, since the sub-key is lost.

**Comment by Mysticus92** [comment]
Funny.
There are new comments despite this thread is closed.
Anyway the downloaded data files of Assault Lily are stored in some server so does anyone know a way to get all visible data from the smartphone? Or is there some resouce site?
I know it's a bit off topic. But some help is appreciated.

**Comment by gbf-dtb** [comment]
If your phone is rooted, you can view all the downloaded assets on the phone itself with file explorers that can get root access (eg. MiXplorer), they're in /data/data/jp.co.allb/files/<MD5 hash>/<MD5 hash> (the larger folder) on Android. There's a button in-game to force the game to download all assets so they should all be in there after you do that. If you end up having to do this on the PC you'll might be better off downloading the PC version on DMM since you won't have to waste time transferring the files from your phone (game data can be linked).

The filenames are all MD5 hashed so you'll need to append .awb extensions to the appropriate filenames, either by trial and error or using some script/tool that renames only certain files (I used grep to look for files with bytes 0x80 and 0x00 at 0x20 and 0x21 offsets for ADX AWBs). They don't store any useful information regarding the original filenames so you'll need something else for that, maybe some manifest file store on their servers.

If you mean fetching all the files directly from the servers you'll probably need to write a tool or wait for someone to do it for this game.
