### ISSUE TITLE
(Request) Please, add support for Halo 2's .dat files

### ISSUE THREAD

**Issue by Simo311** [vgmstream/vgmstream#824]
Could you please add support for .dat audio files from Halo 2?
Halo 2's .dat file is used for certain audio files type (mainly voicelines).
Here a sample of the file:

https://drive.google.com/file/d/11a3UOzJxFwAra5KYwDnFXgjh7fgXJlV4/view?usp=sharing

I sincerely thank you!

**Comment by bnnm** [comment]
It looks like a bunch of things pasted together, that cannot be played as-is. There should be some kind of index file nearby.

**Comment by Simo311** [comment]
Honestly, i'm really not sure how to find what you need, but after a short research among game files, i've found the most likely one -> https://drive.google.com/file/d/13xWy0DNFXVUlYUhGHOGfxxEa8536hEQX/view?usp=sharing

I have no idea if you can get anything out of it.
Anyway i'm willing to upload the entire game folder for you to download it, but it's pretty sized.
Thank for your time!

**Comment by bnnm** [comment]
Nothing on those. Looking at the game's filelist there is nothing like an index either, maybe index is baked into the maps.

Since it's not really an audio format there isn't much vgmstream can do here. I suggest trying "Halo 2 Sound Tools" that apparently import/export sounds, or maybe asking around modding communities
