### ISSUE TITLE
TXTP parsing with absolute filepaths inside failure

### ISSUE THREAD

**Issue by TOPMukS** [vgmstream/vgmstream#839]
Hello, 
thank you for useful component!

I have a problem. I try to use vgmstream foobar component for playing parts of music tracks.
It is ok If I make TXTP file in directory (or subdir) that contains music file, for example: 
D:\\Music\song.mp3            is existing
D:\\Music\partofsong.txtp   is existing and contains:
song.mp3 #r 10.0
(partofsong.txtp on the C: drive)

But component does not work if I make TXTP file (with absolete file path inside) on other disk , for example:
D:\\Music\song.mp3            is existing
C:\\partofsong.txtp              is existing and contains:
D:\\Music\song.mp3 #r 10.0

I read the documentation but did not find the solution of this problem.

Best regards,
Sergey Tormasin

**Comment by bnnm** [comment]
Latest vgmstream should handle those paths: https://vgmstream.org/downloads

However, note that absolute paths aren't mentioned in the docs (only relative paths). That's because they aren't officially supported, since it's hard to unify between different OSs and plugins. So if some future foobar version stops supporting absolute paths there isn't much we can do.

An alternative (for advanced users) in that case is making a "symlink", that behaves like a relative path but can point to any dir.
