### ISSUE TITLE
Multiple files at once?

### ISSUE THREAD

**Issue by Belgaron** [vgmstream/vgmstream#849]
Can this be used on an entire folder? I'm not a commandline pro so I don't know how. Little help?

**Comment by bnnm** [comment]
I think it would be easier if you install foobar2000 + vgmstream plugin. You can open folders to read all files then right click > convert

Otherwise unzip this file near your audio, copy test.exe and .dll together and double click to convert all to wav: 
[vgmstream-batch.zip](https://github.com/vgmstream/vgmstream/files/6416931/vgmstream-batch.zip)

**Comment by Belgaron** [comment]
Thank you for the feedback, foobar200 + vgmstream component isn't working. It's installed but fails to play the files. I will have to try the batch.zip

**Comment by Belgaron** [comment]
The batch file worked. Saved me 18,000 repetitions of mind-numbing drag and drop =]

Will be very useful in the future as well.
