### ISSUE TITLE
OGG Vorbis: Loop End Point Ignored When Implemented

### ISSUE THREAD

**Issue by mistersiraj11** [vgmstream/vgmstream#863]
Hi. For some reason, whenever I add the loop end point of my song, vgmstream completely ignores it, plays the whole song, and loops back to the loop start point. This issue never occurs with OGG Opus and FLAC, so what's the deal here? I tested it with both foobar2000 and Winamp.

The files are posted below.
[Castle Center (LFLAC-LOGG-LOPUS) (Castlevania 64).zip](https://github.com/vgmstream/vgmstream/files/6489877/Castle.Center.LFLAC-LOGG-LOPUS.Castlevania.64.zip)

**Comment by kode54** [comment]
The tag scanner is broken. It expects the `LOOP_START` or `LOOP_BEGIN` tag to somehow be exactly before the `LOOP_END` tag. Since many taggers sort tags in alphabetical order, this won't work with `LOOP_START`, but it will work with the believed pair tag, `LOOP_BEGIN`. Try `LOOP_BEGIN` on the Vorbis file.

This should be filed as an issue, in case the end tag is enumerated before the start tag.

The Opus/FLAC ones don't have this problem because they look up the exact tags by name from a dictionary, rather than looping over them in order in a single pass.

**Comment by bnnm** [comment]
Should work now: https://vgmstream.org/downloads

**Comment by mistersiraj11** [comment]
I'll test it later. I'll close this issue myself if it is fixed.

**Comment by mistersiraj11** [comment]
UPDATE: Yep! The loop end point issue is fixed! Thanks @bnnm and @kode54!
