### ISSUE TITLE
[Bug] Wrong Bitrate for Wwise Vorbis Codec

### ISSUE THREAD

**Issue by meowmore** [vgmstream/vgmstream#955]
i was messing around with some .wem files
and i found out that vgmstream prints wrong bitrate for Wwise Vorbis codec

First, Download this zip file: [Downlaod](https://www.mediafire.com/file/yqdsoc7jeyambkt/wwise_vorsib_wrong_bitrate.zip/file) [21kb]
there is two file in this zip, **dialog_1.wem** **and dialog_2.wem**

both files are same!
dialog_1.wem is untouched,
**dialog_1.wem**
`bitrate: 51 kbps`
actually, real bitrate is 48, not 51! it's wrong (i converted by wwise with 48kbps)

in dialog_2.wem, i just added a null chunk to file
`bitrate: 1125 kbps`
see? bitrate is 1125kbps?! there is a bug or problem
(again, dialog_2.wem is dialog_1.wem but with null chunk)

**Comment by bnnm** [comment]
vgmstream shows the "file bitrate" (counts all data) as opposed to "codec bitrate" (counts pure audio-only parts). I guess you expected the latter.

Calculating 100% correct codec bitrate usually needs to manually read the whole file, slowing down opening files and needing extra effort by devs for minimal benefit, so it's usually not done.

File bitrate isn't "wrong" either, since bigger/bloated files = transfer more data = higher bit rate (games want smaller files, not just smaller codecs).

In some cases it's debatable what's really the codec bitrate. Unlike MP3/AAC, 48kbps of Vorbis data is unplayable/unusable unless it's packed into .ogg/wem/etc with extra data (that does increase final bitrate), so 51kpbs makes sense to me.

The second case could be changed to also output 51kpbs if we only count "data" chunk I guess, though similarly I don't feel bloated files showing bloated bitrate is "wrong" (surprising I agree).

**Comment by meowmore** [comment]
well, by codec i mean file bitrate, thats right
but saying that 51kbps makes sense is wrong, i have reason for that
download this zip: [Download](https://www.mediafire.com/file/dnrlgqeo7n3bmb3/125kbps_test.zip/file)
all files are same (they are 125kbps in Wwise SDK)

in 125kpbs.wem, vgmstream bitrate is 124kbps
in empty_125kbps.wem, bitrate is 1kbps! but it's 125kbps.wem with removed frames,
and wierd thing is that in appended_zeros_empty_125kbps.wem, bitrate is 2kbps
so maybe 51kbps in my first message is actually 48kbps in vgmstream but it calculated it in wrong way, right?


and you said that 51kbps making sense, right, but i converted this files by Wwise, just check the results
[Download Bitrate Test](https://www.mediafire.com/file/zvq4gkifhjahl8u/bitrate_tests.zip/file)

**51kbps.wem** = (vgmstream bitrate = 54kbps)
**126kbps.wem** = (vgmstream bitrate = 126kbps) TOTALY RIGHT?!
**127kbps.wem** = (vgmstream bitrate = 126kbps) 126 again?
**128kbps.wem** = (vgmstream bitrate = 127kbps) wierd, huh?

note: i know that you cleared everything in your comment, but i just reported this to make it clearer

**Comment by kode54** [comment]
And to determine the "correct" bitrate, it would have to completely parse the entire stream. Every time the file is opened.

**Comment by bnnm** [comment]
@meowmore - I think you misunderstand Wwise's settings and end results. It's normal for a silent file to be 1/2kbps, and generally bitrate won't be exact to the Wwise settings since Vorbis is a VBR codec and final bitrate is rounded down.

Why don't you try to manually calculate bitrate for some of your examples and post the calculations and numbers? That will make it easier to see the exact differences.
