### ISSUE TITLE
[Bug] XWB (Stardew Valley): Not all sample names are displayed; samples loop

### ISSUE THREAD

**Issue by 7automaton** [vgmstream/vgmstream#986]
Hello,

When dropping a Stardew Valley XACT Wavebank into foobar2000 with the extension:

* Most audio is displayed conveniently, but some audio is missing names.
* For some reason, the audio samples' `trackIndex` starts at 1 instead of 0. Since it's converting hex codes to decimals, the sample should start at `Wave Bank#0` and increment, but it instead starts at `Wave Bank#1`, resulting in displaying all of the audio samples' in-game IDs incremented by 1.
  * `00000000` is being converted to `Wave Bank#1`, `0000005e` is being converted to `Wave Bank#95`, and so on.
* Lastly, for some odd reason, samples are being looped and replayed within the file itself. The sample should only be played once within the file.
  * If the sample is shorter than 12 seconds, then it will loop for about 12 seconds.
  * Samples that are longer than 12 seconds (music, for instance) will repeat twice within the file.

![image](https://user-images.githubusercontent.com/56928485/138005585-83898656-9329-4bab-9a54-93de322325d0.png)

**Comment by bnnm** [comment]
The #(number) is not a game ID, simply a subsong number from 1..N ("Nth song"). It starts from 1 ("first song") since most users wouldn't be used to programming's 0-index. You can configure the title output in foobar (vgmstream config > override title + Display > User Interface) btw.

For names and loops you'd need to post the whole xwb and xsb to check. Loop info typically comes from files themselves though (barring bugs) so probably they are like that. You can configure number of default loops in config too, set "ignore looping" to disable ([also](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#foo_input_vgmstream-foobar2000-plugin)).
